name: Al_copper
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  line_icons: ^2.0.0
  fl_chart: ^0.68.0
  intl: ^0.19.0
  google_fonts: ^4.0.0
  firebase_core: ^3.11.0
  firebase_auth: ^5.4.2
  cloud_firestore: ^5.6.2
  url_launcher: ^6.3.1
  pay: ^1.0.10
  cupertino_icons: ^1.0.8
  razorpay_flutter: ^1.3.7
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/images/B1.png
    - lib/images/B2.png
    - lib/images/B3.png
    - lib/images/B4.png
    - lib/images/B5.png
    - lib/images/B6.png
    - lib/images/B7.png
